#ifndef SDLW_INCLUDED
#define SDLW_INCLUDED

#include <sdlw/assert.hpp>
#include <sdlw/audio.hpp>
#include <sdlw/blend_mode.hpp>
#include <sdlw/clipboard.hpp>
#include <sdlw/cpu_info.hpp>
#include <sdlw/error.hpp>
#include <sdlw/events.hpp>
#include <sdlw/filesystem.hpp>
#include <sdlw/game_controller.hpp>
#include <sdlw/gesture.hpp>
#include <sdlw/haptic.hpp>
#include <sdlw/hints.hpp>
#include <sdlw/joystick.hpp>
#include <sdlw/keyboard.hpp>
#include <sdlw/keycode.hpp>
#include <sdlw/loadso.hpp>
#include <sdlw/log.hpp>
#include <sdlw/message_box.hpp>
#include <sdlw/mouse.hpp>
#include <sdlw/pixels.hpp>
#include <sdlw/platform.hpp>
#include <sdlw/power.hpp>
#include <sdlw/rect.hpp>
#include <sdlw/render.hpp>
#include <sdlw/rwops.hpp>
#include <sdlw/scancode.hpp>
#include <sdlw/sensor.hpp>
#include <sdlw/subsystem.hpp>
#include <sdlw/surface.hpp>
#include <sdlw/timer.hpp>
#include <sdlw/touch.hpp>
#include <sdlw/types.hpp>
#include <sdlw/version.hpp>
#include <sdlw/video.hpp>

#endif // SDLW_INCLUDED
